FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Program.cs", "."]
COPY ["SaaSFramework.Gateway.csproj", "."]
RUN dotnet restore "SaaSFramework.Gateway.csproj"
COPY . .
RUN dotnet build "SaaSFramework.Gateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SaaSFramework.Gateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SaaSFramework.Gateway.dll"]
